const config = {
  darkMode: ["class"],
  content: [
    "./pages/**/*.{js,jsx,ts,tsx}",
    "./components/**/*.{js,jsx,ts,tsx}",
    "./app/**/*.{js,jsx,ts,tsx}",
    "./src/**/*.{js,jsx,ts,tsx}",
  ],
  prefix: "",
  theme: {
    container: {
      center: true,
      padding: "2rem",
      screens: {
        "2xl": "1440px",
      },
    },
    extend: {
      colors: {
        border: "var(--border)",
        input: "var(--input)",
        ring: "var(--ring)",
        background: "var(--background)",
        foreground: "var(--foreground)",
        primary: {
          DEFAULT: "var(--primary)",
          foreground: "var(--primary-foreground)",
        },
        secondary: {
          DEFAULT: "var(--secondary)",
          foreground: "var(--secondary-foreground)",
        },
        destructive: {
          DEFAULT: "var(--destructive)",
          foreground: "var(--destructive-foreground)",
        },
        muted: {
          DEFAULT: "var(--muted)",
          foreground: "var(--muted-foreground)",
        },
        accent: {
          DEFAULT: "var(--accent)",
          foreground: "var(--accent-foreground)",
        },
        popover: {
          DEFAULT: "var(--popover)",
          foreground: "var(--popover-foreground)",
        },
        card: {
          DEFAULT: "var(--card)",
          foreground: "var(--card-foreground)",
        },
        brand: {
          navy: "#0F172A",
          slate: "#1E293B",
          blue: "#2563EB",
          light: "#FAFAFA",
        },
        "outline": "var(--outline, #76777d)",
        "on-surface": "var(--on-surface, #0b1c30)",
        "on-primary-container": "#7c839b",
        "surface-tint": "#565e74",
        "surface-variant": "var(--surface-variant, #d3e4fe)",
        "on-secondary-container": "#fefcff",
        "surface-dim": "#cbdbf5",
        "on-secondary-fixed": "#00174b",
        "on-primary-fixed-variant": "#3f465c",
        "on-primary": "#ffffff",
        "inverse-primary": "#bec6e0",
        "surface-container": "var(--surface-container, #e5eeff)",
        "tertiary-fixed-dim": "#bcc7de",
        "on-secondary": "#ffffff",
        "on-background": "#0b1c30",
        "primary-fixed": "#dae2fd",
        "primary-container": "#131b2e",
        "on-primary-fixed": "#131b2e",
        "surface-bright": "#f8f9ff",
        "tertiary": "#000000",
        "inverse-surface": "#213145",
        "surface-container-high": "#dce9ff",
        "surface-container-highest": "var(--surface-container-highest, #d3e4fe)",
        "secondary-fixed-dim": "#b4c5ff",
        "on-tertiary-container": "#79849a",
        "on-surface-variant": "var(--on-surface-variant, #45464d)",
        "secondary-container": "#316bf3",
        "tertiary-fixed": "#d8e3fb",
        "on-secondary-fixed-variant": "#003ea8",
        "error": "#ba1a1a",
        "primary-fixed-dim": "#bec6e0",
        "inverse-on-surface": "#eaf1ff",
        "on-tertiary-fixed-variant": "#3c475a",
        "outline-variant": "var(--outline-variant, #c6c6cd)",
        "tertiary-container": "#111c2d",
        "on-error-container": "#93000a",
        "on-tertiary-fixed": "#111c2d",
        "surface-container-low": "var(--surface-container-low, #eff4ff)",
        "secondary-fixed": "#dbe1ff",
        "on-tertiary": "#ffffff",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "surface-container-lowest": "var(--surface-container-lowest, #ffffff)",
        "surface": "var(--surface, #f8f9ff)"
      },
      fontSize: {
        "label-sm": ["12px", { lineHeight: "16px", letterSpacing: "0.02em", fontWeight: "600" }],
        "label-md": ["14px", { lineHeight: "20px", fontWeight: "500" }],
        "helper-text": ["13px", { lineHeight: "18px", fontWeight: "400" }],
        "headline-md": ["24px", { lineHeight: "32px", letterSpacing: "-0.015em", fontWeight: "600" }],
        "headline-sm": ["18px", { lineHeight: "28px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.02em", fontWeight: "600" }],
        "body-md": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "body-lg": ["16px", { lineHeight: "24px", fontWeight: "400" }]
      },
      spacing: {
        "sidebar_width": "260px",
        "sidebar_collapsed": "64px",
        "container_max": "1440px",
        "base": "4px",
        "xs": "0.25rem",
        "sm": "0.5rem",
        "md": "1rem",
        "lg": "1.5rem",
        "xl": "2rem"
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
      fontFamily: {
        sans: ["Inter", "system-ui", "sans-serif"],
        mono: ["Cascadia Code", "Fira Code", "monospace"],
        "label-sm": ["Inter"],
        "label-md": ["Inter"],
        "helper-text": ["Inter"],
        "headline-md": ["Inter"],
        "headline-sm": ["Inter"],
        "headline-lg": ["Inter"],
        "body-md": ["Inter"],
        "body-lg": ["Inter"]
      },
      keyframes: {
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
        fadeIn: {
          "0%": { opacity: "0", transform: "translateY(4px)" },
          "100%": { opacity: "1", transform: "translateY(0)" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
        "pulse-slow": "pulse 3s cubic-bezier(0.4, 0, 0.6, 1) infinite",
        "fade-in": "fadeIn 0.2s ease-out",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
};

module.exports = config;
