export const QUERY_KEYS = {
  ME: ["me"],
  JOBS: ["jobs"],
  JOB: (id) => ["jobs", id],
  SAVED_JOBS: ["savedJobs"],
  APPLICATIONS: ["applications"],
  APPLICATION: (id) => ["applications", id],
  INTERVIEWS: ["interviews"],
  INTERVIEW: (id) => ["interviews", id],
  OFFERS: ["offers"],
  OFFER: (id) => ["offers", id],
  NOTIFICATIONS: ["notifications"],
  NOTIFICATION: (id) => ["notifications", id],
  UNREAD_COUNT: ["notifications", "unread"],
  COMPANY: ["company"],
  COMPANY_BY_ID: (id) => ["company", id],
  USERS: ["users"],
  USER: (id) => ["users", id],
  ADMIN_STATS: ["admin", "stats"],
  RECRUITER_STATS: ["recruiter", "stats"],
  CANDIDATE_STATS: ["candidate", "stats"],
  PENDING_COMPANIES: ["admin", "companies", "pending"],
};
